config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "notes#index"
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :content
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :set_note, only: %i[ show edit update destroy ]
    # validate user is logged in
    before_action :authenticate_user!
    def index
        @notes = Note.all
    end
    def show
    end
    def new
        @note = Note.new
    end
    def create
        @note = Note.new(note_params)
        if @note.save
            redirect_to @note, notice: "Note was successfully created."
        else
            render :new, status: :unprocessable_entity
        end
    end
    def edit
    end
    def update
        if @note.update(note_params)
            redirect_to @note, notice: "Note was successfully updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @note.destroy
        redirect_to notes_url, notice: "Note was successfully destroyed."
    end
    private
    def note_params
        params.require(:note).permit(:title, :content, :user_id)
    end
    private
    def set_note
        @note = Note.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
        <% if user_signed_in? %>
      <p>Logged in as <%= current_user.email %></p>
    <%=button_to "Sign Out", destroy_user_session_path, method: :delete%>
 
    <% else %>

    <%=link_to "Sign In", new_user_session_path%>
    <%=link_to "Sign Up", new_user_registration_path%>
    <%end%>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%=form_with model: @note, local: true do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%# Action Text %>
    <%= form.rich_text_area :content %>
    
  </div>
  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', notes_path %>

app/views/notes/edit.html.erb
<div>
    <h1>Edit Note</h1>
    <%= render 'form', note: @note %>
</div>

app/views/notes/index.html.erb
<div>
    <h1>All Notes</h1>
    <ul>
        <% @notes.each do |note| %>
            <li><%= link_to note.title, note_path(note) %></li>
        <% end %>
    </ul>
    <%= link_to "New Note", new_note_path %>

</div>

app/views/notes/new.html.erb
<div>
    <h1>New Note</h1>
    <%= render 'form', note: @note %>
</div>

app/views/notes/show.html.erb
<div>
    <h1><%= @note.title %></h1>
    <p><%= @note.content %></p>
    <%= link_to 'Edit', edit_note_path(@note) %> |
    <%= link_to 'Back', notes_path %>
    <%=button_to 'Delete', note_path(@note), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>